//Apartat b.

CREATE TABLE regions(
    REGION_ID NUMBER CONSTRAINT reg_region_id_pk PRIMARY KEY,
    REGION_NAME VARCHAR2(50 BYTE) CONSTRAINT reg_regio_name_nn NOT NULL
    );
    
    
CREATE TABLE countries(
    COUNTRY_ID CHAR(2 BYTE) CONSTRAINT cou_country_id_pk PRIMARY KEY,
    COUNTRY_NAME VARCHAR2(40 BYTE) CONSTRAINT cou_country_name_nn NOT NULL,
    REGION_ID NUMBER CONSTRAINT cou_region_id_fk REFERENCES REGIONS(REGION_ID) ON DELETE SET NULL
    );
    
CREATE TABLE locations(
    LOCATION_ID NUMBER CONSTRAINT loc_location_id_pk PRIMARY KEY,
    ADDRESS VARCHAR2(255 BYTE) CONSTRAINT loc_address_nn NOT NULL,
    POSTAL_CODE VARCHAR2(20 BYTE),
    CITY VARCHAR2(50 BYTE),
    STATE VARCHAR2(50 BYTE),
    COUNTRY_ID CHAR(2 BYTE) CONSTRAINT loc_country_id_fk REFERENCES COUNTRIES ON DELETE SET NULL
    );

