-- Borrem totes les relacions i restriccions
DROP TABLE regions CASCADE CONSTRAINTS;
DROP TABLE countries CASCADE CONSTRAINTS;
DROP TABLE locations CASCADE CONSTRAINTS;
DROP TABLE inventories CASCADE CONSTRAINTS;
DROP TABLE warehouses CASCADE CONSTRAINTS;
DROP TABLE products CASCADE CONSTRAINTS;

-- Apartat b.

CREATE TABLE regions(
    REGION_ID NUMBER CONSTRAINT reg_region_id_pk PRIMARY KEY,
    REGION_NAME VARCHAR2(50 BYTE) CONSTRAINT reg_regio_name_nn NOT NULL
    );
    
    
CREATE TABLE countries(
    COUNTRY_ID CHAR(2 BYTE) CONSTRAINT cou_country_id_pk PRIMARY KEY,
    COUNTRY_NAME VARCHAR2(40 BYTE) CONSTRAINT cou_country_name_nn NOT NULL,
    REGION_ID NUMBER CONSTRAINT cou_region_id_fk REFERENCES REGIONS(REGION_ID) ON DELETE SET NULL
    );
    
CREATE TABLE locations(
    LOCATION_ID NUMBER CONSTRAINT loc_location_id_pk PRIMARY KEY,
    ADDRESS VARCHAR2(255 BYTE) CONSTRAINT loc_address_nn NOT NULL,
    POSTAL_CODE VARCHAR2(20 BYTE),
    CITY VARCHAR2(50 BYTE),
    STATE VARCHAR2(50 BYTE),
    COUNTRY_ID CHAR(2 BYTE) CONSTRAINT loc_country_id_fk REFERENCES COUNTRIES ON DELETE SET NULL
    );

/*
A continuació ficaré les sentències de creació dels
apartats c,d i e
*/

CREATE TABLE inventories(
    QUANTITY NUMBER
);

CREATE TABLE warehouses(
    WAREHOUSE_ID NUMBER CONSTRAINT war_warehouse_id_pk PRIMARY KEY,
    WAREHOUSE_NAME VARCHAR2(255 BYTE),
    LOCATION_ID NUMBER(12) CONSTRAINT war_location_id_fk REFERENCES LOCATIONS ON DELETE SET NULL
    );
    
CREATE TABLE products(
    PRODUCT_ID NUMBER CONSTRAINT pro_product_id_pk PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(255 BYTE) CONSTRAINT pro_product_name_nn NOT NULL,
    DESCRIPTION VARCHAR2(2000 BYTE),
    STANDARD_COST NUMBER(9, 2),
    LIST_PRICE NUMBER(9, 2));
